Calendar, Categories, and End Dates
EmuMan/stay-soft pull request #48
Opened 2024-03-08 00:27 UTC by Gabe-Alonso

Adds Calendar input for dateClosed. dateClosed and Category correctly appear in prompts in the feed

2024-03-08 02:29 UTC, 1colinmcdonald commented
It's not passing the checks. I'm not the expert on the CI/CD though.

2024-03-08 02:31 UTC, 1colinmcdonald requested changes
I think it would be a good idea for it to pass the CI/CD checks.

2024-03-08 04:05 UTC, EmuMan approved these changes
Fixed the issue with dependencies, all tests pass now.

2024-03-08 06:57 UTC, Thundderr approved these changes
Seems to work with CI/CD, and no merge conflicts. Code looks good!

2024-03-08 07:17 UTC, Thundderr commented
Merge resolved and deploys 👍

2024-03-08 16:19 UTC, 1colinmcdonald approved these changes
Looks good

2024-03-09 00:03 UTC, svenlinus commented on .vscode/settings.json
> +{
What is this file? If it is empty it should not be included in the pr. One could add it to the .gitignore

2024-03-09 00:03 UTC, svenlinus commented on packages/express-backend/services.js
> +  console.log(prompt);
Are these debug statements still necessary.

2024-03-09 00:03 UTC, svenlinus commented on packages/react-frontend/src/components/Bet.js
> +function Bet(props) {
Nice

2024-03-09 00:03 UTC, svenlinus commented on packages/react-frontend/src/components/Prompt.js
> +            You cannot vote on your own prompt.
Vote is not the right word here. Maybe bet?

2024-03-09 00:03 UTC, svenlinus commented on packages/react-frontend/src/components/QuestionForm.js
> +    question: ""
There is no need for these hooks to be objects, they could all be string.
i.e.
const [question, setQuestion] = useState("");

2024-03-09 00:03 UTC, svenlinus commented on packages/react-frontend/src/components/QuestionForm.js
> +        setQuestion({ question: value });
And then
setQuestion(value);

2024-03-09 00:03 UTC, svenlinus commented on packages/react-frontend/src/components/QuestionForm.js
> +    }
And then
{
question: question,
category: categort
...
}

2024-03-12 00:00 UTC, merged